# Generated by Django 4.1 on 2023-05-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizzes"},
        ),
        migrations.AlterModelOptions(
            name="useranswermap",
            options={"verbose_name_plural": "UserAnswerMaps"},
        ),
        migrations.AlterModelOptions(
            name="userquizsession",
            options={"verbose_name_plural": "UserQuizSessions"},
        ),
    ]
