# Generated by Django 4.1 on 2023-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_question_option_1_question_option_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswermap",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useranswermap",
            name="saved",
            field=models.BooleanField(default=False),
        ),
    ]
