# Generated by Django 4.1 on 2023-05-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_useranswermap_is_correct_useranswermap_saved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswermap",
            name="user_answer",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
