# Generated by Django 4.1 on 2023-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_userquizsession_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="duration",
            field=models.IntegerField(default=10),
        ),
    ]
